### PR TITLE
Fix missing break lines in get_db_snr_map()

### PR DESCRIPTION
**Pull request by lars18th**
Fixes coverity errors introduced with PR https://github.com/catalinii/minisatip/pull/912#issuecomment-1003441533

### CODE REVIEW

**Comment by lars18th** [comment]
Hi @catalinii ,

In my repo the coverity test over mips platform returns this error:
```
mipsel-tuxbox-linux-gnu-gcc -Wall -Wno-switch -ggdb -fPIC   -DMINOR=\"\" -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI -DENIGMA -c dvb.c -o ../build/dvb.o
dvb.c: In function 'get_db_snr_map':
dvb.c:353:10: error: 'SYS_DVBC_ANNEX_C' undeclared (first use in this function)
     case SYS_DVBC_ANNEX_C: /* not sure, to be tested */
          ^
dvb.c:353:10: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:155: ../build/dvb.o] Error 1
make[1]: Leaving directory '/__w/minisatip/minisatip/src'
make: *** [Makefile:11: minisatip] Error 2
```

I want to hear your opinion: You prefer to remove the case `SYS_DVBC_ANNEX_C` from the code? I feel this modulation is not used with minisatip, and if we remove it then other ancient mips platforms (E2) will not fail to compile.

You agree with this additional change?

**Comment by lars18th** [comment]
Hi @catalinii ,

I finally removed the SYS_DVBC_ANNEX_C from get_db_snr_map() too to fix https://github.com/catalinii/minisatip/runs/4675651488?check_suite_focus=true

So, it's ready to merge. Please check it!
