### ISSUE TITLE
Compile with vdr_plugin_mcli 0.9.7 / undefined reference to m_logskipmask and m_debugmask

### ISSUE THREAD

**Issue by troem** [catalinii/minisatip#947]
If I try to compile minisatip with current version of mcli, using the following parameter:
--enable-netceiver=yes --with-mcli --with-xml2

I am receiving during make the following error-messages:
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libmcli.so: undefined reference to `m_logskipmask'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libmcli.so: undefined reference to `m_debugmask'
```

Thank you for any help.

**Comment by Jalle19** [comment]
Where exactly would I find `libmcli` if I wanted to build with `--with-mcli`? It is rare to find something so utterly undocumented as the Netceiver...

**Comment by troem** [comment]
You can find the libmcli in the subfolder /mcast/client if you compile the vdr-plugin-mcli e.g. from https://github.com/vdr-projects/vdr-plugin-mcli

**Comment by Jalle19** [comment]
AFAICT this was fixed in https://github.com/catalinii/minisatip/pull/964/files#diff-2380806ee42704fa301aee4fac4261d8780b6653fafad85c1aec56caa43bc902R41
